GestionVehicular/Controllers/RolesController.cs
using Microsoft.EntityFrameworkCore;

namespace GestionVehicular.Controllers;

[Authorize]
public class RolesController : Controller
{
    private readonly ApplicationDbContext _context;

    public RolesController(ApplicationDbContext context)
    {
        _context = context;
    }

    // GET: Roles
    public async Task<IActionResult> Index()
    {
        return View(await _context.Roles.ToListAsync());
    }

    // GET: Roles/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null || _context.Roles == null)
        {
            return NotFound();
        }

        var role = await _context.Roles
            .FirstOrDefaultAsync(m => m.RolId == id);
        if (role == null)
        {
            return NotFound();
        }

        return View(role);
    }

    // GET: Roles/Create
    public IActionResult Create()
    {
        return View();
    }

    // POST: Roles/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("RolId,Nombre,EsActivo,FechaCreacion")] Role role)
    {
        if (ModelState.IsValid)
        {
            role.EsActivo = true;
            role.FechaCreacion = DateTime.Now;
            _context.Add(role);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        return View(role);
    }

    // GET: Roles/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null || _context.Roles == null)
        {
            return NotFound();
        }

        var role = await _context.Roles.FindAsync(id);
        if (role == null)
        {
            return NotFound();
        }
        return View(role);
    }

    // POST: Roles/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("RolId,Nombre,EsActivo,FechaCreacion")] Role role)
    {
        if (id != role.RolId)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                _context.Update(role);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!RoleExists(role.RolId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
        return View(role);
    }

    // GET: Roles/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null || _context.Roles == null)
        {
            return NotFound();
        }

        var role = await _context.Roles
            .FirstOrDefaultAsync(m => m.RolId == id);
        if (role == null)
        {
            return NotFound();
        }

        return View(role);
    }

    // POST: Roles/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        if (_context.Roles == null)
        {
            return Problem("Entity set 'ApplicationDbContext.Roles'  is null.");
        }
        var role = await _context.Roles.FindAsync(id);
        if (role != null)
        {
            _context.Roles.Remove(role);
        }

        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private bool RoleExists(int id)
    {
        return _context.Roles.Any(e => e.RolId == id);
    }
}

GestionVehicular/Controllers/UsuariosController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace GestionVehicular.Controllers;

[Authorize]
public class UsuariosController : Controller
{
    private readonly ApplicationDbContext _context;

    public UsuariosController(ApplicationDbContext context)
    {
        _context = context;
    }

    // GET: Usuarios
    public async Task<IActionResult> Index()
    {
        var applicationDbContext = _context.Usuarios.Include(u => u.Rol).Include(u => u.Subcircuito);
        return View(await applicationDbContext.ToListAsync());
    }

    // GET: Usuarios/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null || _context.Usuarios == null)
        {
            return NotFound();
        }

        var usuario = await _context.Usuarios
            .Include(u => u.Rol)
            .Include(u => u.Subcircuito)
            .FirstOrDefaultAsync(m => m.UsuarioId == id);
        if (usuario == null)
        {
            return NotFound();
        }

        return View(usuario);
    }

    // GET: Usuarios/Create
    public IActionResult Create()
    {
        ViewData["RolId"] = new SelectList(_context.Roles, "RolId", "Nombre");
        ViewData["SubcircuitoId"] = new SelectList(_context.Set<Subcircuito>(), "SubcircuitoId", "Nombre");
        return View();
    }

    // POST: Usuarios/Create
    // To protect from over posting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("UsuarioId,Cedula,Contrasenia,Nombre,Apellido,FechaNacimiento,TipoSangre,Telefono,CiudadNacimiento,Rango,EsActivo,RolId,SubcircuitoId,FechaCreacion")] Usuario usuario)
    {
        if (ModelState.IsValid)
        {
            usuario.EsActivo = true;
            usuario.FechaCreacion = DateTime.Now;
            usuario.Contrasenia = BCrypt.Net.BCrypt.HashPassword(usuario.Contrasenia);
            _context.Add(usuario);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        ViewData["RolId"] = new SelectList(_context.Roles, "RolId", "Nombre", usuario.RolId);
        ViewData["SubcircuitoId"] = new SelectList(_context.Set<Subcircuito>(), "SubcircuitoId", "CodSubcircuito", usuario.SubcircuitoId);
        return View(usuario);
    }

    // GET: Usuarios/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null || _context.Usuarios == null)
        {
            return NotFound();
        }

        var usuario = await _context.Usuarios.FindAsync(id);
        if (usuario == null)
        {
            return NotFound();
        }
        ViewData["RolId"] = new SelectList(_context.Roles, "RolId", "Nombre", usuario.RolId);
        ViewData["SubcircuitoId"] = new SelectList(_context.Set<Subcircuito>(), "SubcircuitoId", "Nombre", usuario.SubcircuitoId);
        return View(usuario);
    }

    // POST: Usuarios/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("UsuarioId,Cedula,Contrasenia,Nombre,Apellido,FechaNacimiento,TipoSangre,Telefono,CiudadNacimiento,Rango,EsActivo,RolId,SubcircuitoId,FechaCreacion")] Usuario usuario)
    {
        if (id != usuario.UsuarioId)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                usuario.Contrasenia = BCrypt.Net.BCrypt.HashPassword(usuario.Contrasenia);
                _context.Update(usuario);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!UsuarioExists(usuario.UsuarioId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
        ViewData["RolId"] = new SelectList(_context.Roles, "RolId", "Nombre", usuario.RolId);
        ViewData["SubcircuitoId"] = new SelectList(_context.Set<Subcircuito>(), "SubcircuitoId", "CodSubcircuito", usuario.SubcircuitoId);
        return View(usuario);
    }

    // GET: Usuarios/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null || _context.Usuarios == null)
        {
            return NotFound();
        }

        var usuario = await _context.Usuarios
            .Include(u => u.Rol)
            .Include(u => u.Subcircuito)
            .FirstOrDefaultAsync(m => m.UsuarioId == id);
        if (usuario == null)
        {
            return NotFound();
        }

        return View(usuario);
    }

    // POST: Usuarios/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        if (_context.Usuarios == null)
        {
            return Problem("Entity set 'ApplicationDbContext.Usuarios'  is null.");
        }
        var usuario = await _context.Usuarios.FindAsync(id);
        if (usuario != null)
        {
            _context.Usuarios.Remove(usuario);
        }

        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private bool UsuarioExists(int id)
    {
        return _context.Usuarios.Any(e => e.UsuarioId == id);
    }
}

GestionVehicular/Views/Shared/_Layout.cshtml
@using System.Security.Claims;
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gestión Vehicular</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GestionVehiculos.styles.css" asp-append-version="true" />
</head>

@{
    string role = User.FindFirstValue(ClaimTypes.Role);
}

<body>
    <header>
        <nav class="navbar navbar-dark bg-dark">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="offcanvas offcanvas-start bg-dark" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
                    <div class="offcanvas-header">
                        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Offcanvas</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                    </div>
                    <div class="offcanvas-body">
                        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                            <li class="nav-item">
                                <a class="nav-link text-warning" asp-area="" asp-controller="Home"
                                   asp-action="Index">Home</a>
                            </li>
                            @if (role == "Administrador")
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Módulo de Distritos
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li class="dropdown-item">
                                            <a class="dropdown-item text-primary" asp-area="" asp-controller="Distritos"
                                           asp-action="Index">Distritos</a>
                                        </li>
                                        <li>
                                            <hr class="dropdown-divider">
                                        </li>
                                        <li class="dropdown-item">
                                            <a class="dropdown-item text-primary" asp-area="" asp-controller="Circuitos"
                                           asp-action="Index">Circuitos</a>
                                        </li>
                                        <li>
                                            <hr class="dropdown-divider">
                                        </li>
                                        <li class="dropdown-item">
                                            <a class="dropdown-item text-primary" asp-area="" asp-controller="Subcircuitos"
                                           asp-action="Index">Subcircuitos</a>
                                        </li>
                                    </ul>
                                </li>
                            }
                            @if (role == "Administrador" || role == "Técnico 1" || role == "Técnico 2")
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Módulo de Solicitudes
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li class="dropdown-item">
                                            <a class="nav-link text-primary" asp-area="" asp-controller="Mantenimientos"
                                           asp-action="Index">Mantenimientos</a>
                                        </li>
                                        <li>
                                            <hr class="dropdown-divider">
                                        </li>
                                        <li class="dropdown-item">
                                            <a class="nav-link text-primary" asp-area="" asp-controller="ParteNovedades"
                                           asp-action="Index">Partes</a>
                                        </li>
                                        <li>
                                            <hr class="dropdown-divider">
                                        </li>
                                        <li class="dropdown-item">
                                            <a class="nav-link text-primary" asp-area="" asp-controller="Abastecimientos"
                                           asp-action="Index">Abastecimientos</a>
                                        </li>
                                        <li>
                                            <hr class="dropdown-divider">
                                        </li>
                                        <li class="dropdown-item">
                                            <a class="nav-link text-primary" asp-area="" asp-controller="Movilizaciones"
                                           asp-action="Index">Movilizaciones</a>
                                        </li>
                                        @if (role == "Administrador" || role == "Técnico 2")
                                        {
                                            <li>
                                                <hr class="dropdown-divider">
                                            </li>
                                            <li class="dropdown-item">
                                                <a class="nav-link text-primary" asp-area="" asp-controller="Aprobaciones"
                                           asp-action="Index">Aprobaciones</a>
                                            </li>
                                        }
                                    </ul>
                                </li>
                            }

                            @if (role == "Administrador")
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Módulo de Administración
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li class="dropdown-item">
                                            <a class="nav-link text-primary" asp-area="" asp-controller="Roles"
                                           asp-action="Index">Roles</a>
                                        </li>
                                        <li>
                                            <hr class="dropdown-divider">
                                        </li>
                                        <li class="dropdown-item">
                                            <a class="nav-link text-primary" asp-area="" asp-controller="Usuarios"
                                           asp-action="Index">Usuarios</a>
                                        </li>
                                        <li>
                                            <hr class="dropdown-divider">
                                        </li>
                                        <li class="dropdown-item">
                                            <a class="nav-link text-primary" asp-area="" asp-controller="Vehiculos"
                                           asp-action="Index">Vehículos</a>
                                        </li>
                                        <li>
                                            <hr class="dropdown-divider">
                                        </li>
                                        <li class="dropdown-item">
                                            <a class="nav-link text-primary" asp-area="" asp-controller="TiposMantenimiento"
                                           asp-action="Index">Tipos de Mantenimiento</a>
                                        </li>
                                        <li>
                                            <hr class="dropdown-divider">
                                        </li>
                                        <li class="dropdown-item">
                                            <a class="nav-link text-primary" asp-area="" asp-controller="TiposSugerencia"
                                           asp-action="Index">Tipos Sugerencias</a>
                                        </li>
                                        <li>
                                            <hr class="dropdown-divider">
                                        </li>
                                        <li class="dropdown-item">
                                            <a class="nav-link text-primary" asp-area="" asp-controller="Sugerencias"
                                           asp-action="Index">Sugerencias</a>
                                        </li>
                                    </ul>
                                </li>
                            }

                            @*<li class="nav-item">
                            <a class="nav-link text-warning" asp-area="" asp-controller="Vehiculos"
                            asp-action="Index">Vehículos</a>
                            </li>*@
                        </ul>
                    </div>
                </div>
                <form id="logoutForm" asp-controller="Account" asp-action="Logout" method="post">
                    <button class="btn btn-outline-warning">
                        Sign out
                    </button>
                </form>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Gestión Vehicular
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

GestionVehicular/Views/Shared/_NoNavLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>@ViewData["Title"] - Gestion Vehicular</title>
  <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
  <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
  <link rel="stylesheet" href="~/GestionVehiculos.styles.css" asp-append-version="true" />
</head>

<body>
  <div class="container">
    <main role="main" class="pb-3">@RenderBody()</main>
  </div>
  <script src="~/lib/jquery/dist/jquery.min.js"></script>
  <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="~/js/site.js" asp-append-version="true"></script>
  @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

